version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
    - "22:22"
    - "80:80"
    - "443:443"
    restart: always
    volumes:
    - /home/alastair/gitlab/config:/etc/gitlab
    - /home/alastair/gitlab/logs:/var/log/gitlab
    - /home/alastair/gitlab/data:/var/opt/gitlab
